#!/bin/sh
set -e


showpubkey() {
    local keyfile="$1" pubkey

    if ! which ssh-keygen >/dev/null 2>&1; then
        cat
    else
        pubkey="$(mktemp --tmpdir -- "${keyfile##*/}-XXXXXXXXXX.pub")"
        grep -m1 -E '^(ssh-(dss|rsa|ed25519)|ecdsa-sha2-nistp(256|384|521)) ' >"$pubkey"
        ssh-keygen -v -lf "$pubkey" | sed -r "1s@\\S+(\\s+\\([^)]+\\))\$@$keyfile\\1@"
        rm -f -- "$pubkey"
    fi
}

move_confdir() {
    local src="/etc/dropbear-initramfs/$1"
    local dest="/etc/dropbear/initramfs/$1"
    if [ -e "$src" ] && [ ! -e "$dest" ]; then
        mv -T -- "$src" "$dest"
    fi
}

if [ "$1" = "configure" ]; then
    if dpkg --compare-versions "$2" lt "2020.81-4~"; then
        for keytype in dss rsa ecdsa ed25519; do
            move_confdir "dropbear_${keytype}_host_key"
        done
        move_confdir "authorized_keys"
        for keytype in dsa rsa ecdsa ed25519; do
            move_confdir "id_${keytype}.pub"
        done
    fi

    havehostkey=no
    for keytype in dss rsa ecdsa ed25519; do
        keyfile="/etc/dropbear/initramfs/dropbear_${keytype}_host_key"
        if [ -e "$keyfile" ]; then
            havehostkey=yes
            break
        fi
    done
    if [ "$havehostkey" = "no" ]; then
        # generate host keys (excluding DSS)
        for keytype in rsa ecdsa ed25519; do
            keyfile="/etc/dropbear/initramfs/dropbear_${keytype}_host_key"
            echo "Generating Dropbear $(echo "$keytype" | tr '[a-z]' '[A-Z]') host key.  Please wait." >&2
            dropbearkey -t "$keytype" -f "$keyfile" | showpubkey "$keyfile"
        done
    fi

    # XXX here we could read the configured network-config, and use it
    # for default values for prompting the user for the
    # initramfs-network- config (subsequently writing it to menu.lst:#
    # kopt= or lilo.conf), instead of just printing the reminder below.
    update-initramfs -u
    if ! grep -Eq '^(.*\s)?ip=' /proc/cmdline; then
        cat <<-EOT
			Dropbear has been added to the initramfs. Don't forget to check
			your "ip=" kernel bootparameter to match your desired initramfs
			ip configuration.

		EOT
    fi
fi

# Automatically added by dh_installdeb/13.6ubuntu1
dpkg-maintscript-helper mv_conffile /etc/dropbear-initramfs/config /etc/dropbear/initramfs/dropbear.conf 2020.81-4\~ -- "$@"
# End automatically added section


if [ "$1" = "configure" ] && [ -d /etc/dropbear-initramfs ] && dpkg --compare-versions "$2" lt "2020.81-4~"; then
    if ! rmdir /etc/dropbear-initramfs; then
        echo "ERROR: Couldn't remove directory /etc/dropbear-initramfs" >&2
    fi
fi
exit 0
