#!/bin/bash
if [[ "$1" == "prebuild" ]]; then
	for FILE in usr/bin/*; do cp -vu /${FILE} usr/bin/; done
	test -f /opt/modify_ubuntu_kit/edit_chroot.sh && cp -vu /opt/modify_ubuntu_kit/edit_chroot.sh usr/bin/edit_chroot
	rm -v ~/GitHub/ppa/all/reddragon-tools_*_all.deb
fi
